services:
  db:
    image: postgres:16.3-alpine3.20
    restart: always
    environment:
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=local_pass
      - POSTGRES_DB=vault
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - postgres_net

volumes:
  db:
    driver: local

networks:
  postgres_net:
    driver: bridge
