name: CI/CD
on:
  push:
    branches: [ feat/auth ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p ~/.config/gh

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.15.1'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup turbo cache
        uses: actions/cache@v3
        with:
          path: '.turbo'
          key: turbo-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.ref_name }}-
            turbo-master-

      - name: Setup git
        env:
          GIT_USER_NAME: ${{ github.actor }}
          GIT_USER_EMAIL: 'action@github.com'
        run: |
          git config user.name "$GIT_USER_NAME"
          git config user.email "$GIT_USER_EMAIL"

      - name: Devcontainer
        uses: devcontainers/ci@v0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          env: |
            GITHUB_TOKEN
          runCmd: |
            bun install --frozen-lockfile --ignore-scripts
            bun run release --cache-dir=.turbo